# Configuration for GRU-DeepONet for Poisson Problem

# Data configuration
data:
  data_dir: "preprocessed_data"
  normalization_method: "maxabs"  # "maxabs" or "standard"

# Training configuration
training:
  seed: 2024
  batch_size: 128
  epochs: 4000
  save_model_every: 1000
  
  # Learning rate schedule
  learning_rate:
    initial: 1.0e-3
    final: 1.0e-5
    scheduler: "warmup_cosine_decay"  # "warmup_cosine_decay", "warmup_linear_decay", or "constant"
  
  # Loss weights (only component 0 for Poisson - scalar output)
  loss_weight_component_0: 1.0
  
  # Lookahead optimizer settings
  use_lookahead: true
  lookahead_alpha: 0.5
  lookahead_k: 6

# Network architecture
network:
  # Branch network (GRU) - size adjusted for parameter parity with NCDE
  branch_hidden_size: 104  # Compensates for GRU vs NCDE parameter differences
  branch_num_layers: 6
  
  # Trunk network (MLP) - must match NCDE trunk
  trunk_hidden_size: 200
  trunk_num_layers: 6

# Paths
paths:
  results: "resultsV2_gru/results"
  model_checkpoints: "model_checkpoints"
  training_metrics_image: "training_metrics_gru.png"